### ISSUE TITLE
Zend\Escaper should be required

### ISSUE THREAD

**Issue by zf2timo** [zendframework/zend-debug#2]
The `Zend\Escaper` Component is in `suggest` and `require-dev` section of the composer. But it is in the `Zend\Debug\Debug` Class as `use` Statement (see https://github.com/zendframework/zend-debug/blob/5fdb2466b18386fc8b4c3afb6cd753b626649856/src/Debug.php#L12).
So `Zend\Escaper` should be a required dependency.

I can send a PR.

**Comment by Ocramius** [comment]
Please do. It should be a dependency, yes.

**Comment by gianarb** [comment]
Yes please send it!! :+1:
